Fixed BingChat to recent APIs changes.
bsdayo/BingChat pull request #41
Opened 2023-10-06 23:23 UTC by gunpal5

Fixed BingChat to recent APIs changes. Now it is absolutely necessary to provide all the Bing Cookies.
Added codes to ensure the conversation is authenticated.
Added retry mechanism on WebSocketException

this commit provide fixes to issues https://github.com/bsdayo/BingChat/issues/40 https://github.com/bsdayo/BingChat/issues/39 https://github.com/bsdayo/BingChat/issues/38 https://github.com/bsdayo/BingChat/issues/36

To use command line tool: 
1) Copy Bing Cookies using Cookies Editor extension and save to a file.
2) Set BING_COOKIES_FILE environment variable by using this command
`set [BING_COOKIES_FILE=[<path to cookies file>]]`
3)  dotnet bingchat

2023-10-07 16:15 UTC, neon-sunset commented
Thank you for the pull request @gunpal5. However, it cannot be merged as is. There are a few points to address first:
- Remove irrelevant comments
- Use JsonSerializerContext instead of reflection-based serialization (`<T>`)
- Double-check if the change to parse the cookie file is necessary - 
- Fix syntax formatting errors
- Remove transient build/IDE files

2023-10-07 19:42 UTC, gunpal5 commented
@neon-sunset I made necessary changes you asked.

Regarding cookie files, I am not sure which cookie Bing is using to authenticate the chat. only passing _U and/or KievRPSSecAuth are not enough. someone else might figure out the right cookies to pass as arguments in `BingChatClientOptions`

2023-11-07 04:24 UTC, gunpal5 commented
@neon-sunset It's been like a month, people need it. Please review and merge

2023-11-07 12:29 UTC, neon-sunset commented
I understand that you would like to have this PR merged.  
But I can't do it because it still has issues and does not approach the problem in a way this library is designed - it reverse engineers original `BingChat` logic and requires to configure only what's actually necessary. Forcing the users to dump all of the cookies being the only way for it to work is a workaround. My suggestion would be inspecting the API interaction flow closer and also checking out what the libraries in other languages do, and then porting their fixes to this PR.

2023-11-07 12:37 UTC, neon-sunset requested changes

2023-11-07 12:37 UTC, neon-sunset commented on .vs/BingChat/FileContentIndex/fabd545b-3a9e-4b0f-9c70-8c16fd4a4260.vsidx
This file does not belong to the PR

2023-11-07 12:37 UTC, neon-sunset commented on src/BingChat/BingChatClient.cs
> +        var encryptedConversationSignature = rawResponse.Headers.GetValues("X-Sydney-EncryptedConversationSignature").FirstOrDefault();
If this doesn't work with `encryptedConversationSignature`, shouldn't it be `First()` instead of `FirstOrDefault()`?

2023-11-07 12:37 UTC, neon-sunset commented on src/BingChat/BingChatConversation.cs
> +        this._cookies = cookies;
```suggestion
        _cookies = cookies;
```

2023-11-07 12:37 UTC, neon-sunset commented on src/BingChat/BingChatConversation.cs
> +            new UriEndPoint(new Uri(uri)),
You need to cache this property instead of creating it on each request.

2023-11-07 12:37 UTC, neon-sunset commented on src/dotnet-bingchat/Utils.cs
> +            CookieFilePath = string.IsNullOrEmpty(cookieFile)? null: cookieFile,
```suggestion
            CookieFilePath = string.IsNullOrEmpty(cookieFile) ? null : cookieFile,
```

2023-11-07 12:37 UTC, neon-sunset commented on src/dotnet-bingchat/dotnet-bingchat.csproj
Please revert all changes in this file.

2023-11-07 12:39 UTC, neon-sunset commented
I'll need to give it another look over some time later with a proper IDE with analyzers.

2023-11-07 12:41 UTC, neon-sunset requested changes

2023-11-07 12:41 UTC, neon-sunset commented on src/BingChat/BingChatConversation.cs
> +                Thread.Sleep(100);
You must never use `Thread.Sleep(...)` in `async` methods or methods that can be called from async. The correct way to do it is to use `Task.Delay(...)`.

2025-02-20 13:13 UTC, closed without merging